account/urls.py
from django.urls import path
from .views import signup, CustomLoginView, logout_form, home_view,CustomPasswordChange, CustomPasswordRest, CustomPasswordResetConfirmView
from django.contrib.auth.views import (LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, PasswordResetConfirmView, PasswordResetDoneView, PasswordResetCompleteView)
from .forms import EmailorPhoneAuthentication

app_name = 'account'

urlpatterns = [
    path('login/', CustomLoginView.as_view(authentication_form=EmailorPhoneAuthentication), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password-change/', CustomPasswordChange.as_view(), name='password_change'),
    path('password-reset/', CustomPasswordRest.as_view(), name='password_reset'),
    path('password-reset/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('password-reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'), 
    #path('verify/', verify_view, name='verify'),
    path('signup/', signup, name='signup'),
    path('logout/form/', logout_form, name='form'),
    path('', home_view, name='home')
]

campus_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from user_profile.views import user_profile

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', include('django.contrib.auth.urls')),
    path('account/', include('account.urls', namespace='account')),
    path('profile/', include('user_profile.urls', namespace='user_profile')),
    path('', include('products.urls', namespace='products')),
    path('social-auth/', include('social_django.urls', namespace='social')),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

products/urls.py
from django.urls import path
from .views import product_list, create_product_view, product_detail, edit_product, delete_product, product_search

app_name = 'products'

urlpatterns = [
    path('', product_list, name='product_list'),
    path('products/<slug:category_slug>/', product_list, name='product_list_slug'),
    path('<int:id>/<slug:slug>', product_detail, name='product_detail'),
    path('post_product/', create_product_view, name='create_product'),
    path('<int:id>/<slug:slug>/edit/', edit_product, name='edit_product'),
    path('<int:id>/<slug:slug>/del/', delete_product, name='delete'),
    path('search/', product_search, name='search')
]

user_profile/urls.py
from django.urls import path
from .views import edit, user_profile

app_name = 'user_profile' 

urlpatterns = [
    path('edit/', edit, name='profile_edit'),
    path('<username>/', user_profile, name='profile')
]

account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager, PermissionsMixin
from phonenumber_field.modelfields import PhoneNumberField
import random
class CustomUserManager(BaseUserManager):
    def create_user(self, email=None, phone_number=None, password=None, **extra_fields):
        if not email and not phone_number:
            raise ValueError('The user must have either email address or phone number')
        if email:
            email = self.normalize_email(email)
        user = self.model(email=email, phone_number=phone_number, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user
    
    def create_superuser(self, email, phone_number, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_user(email, phone_number, password, **extra_fields)
    
class CustomUser(AbstractUser, PermissionsMixin):
    first_name = models.CharField(max_length=25)
    last_name = models.CharField(max_length=25)
    username = models.CharField(unique=True)
    email = models.EmailField(unique=True, null=True, blank=True)
    phone_number = PhoneNumberField(unique=True, null=True, blank=True)
    is_staff = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['phone_number']

    objects = CustomUserManager()

    def __str__(self):
        return self.email or self.phone_number


class Code(models.Model):
    number = models.CharField(max_length=5, blank=True)
    user = models.OneToOneField(
        CustomUser,
        on_delete=models.CASCADE
    )

    def __str__(self):
        return str(self.number)
    
    def save(self, *args, **kwargs):
        number_list = [x for x in range(10)]
        code_items = []

        for i in range(5):
            num = random.choice(number_list)
            code_items.append(num)

        code_string = ''.join(str(item) for item in code_items)
        self.number = code_string
        super().save(*args, **kwargs)

account/forms.py
from django import forms
from .models import CustomUser, Code
from django.contrib.auth.forms import AuthenticationForm, SetPasswordForm, PasswordChangeForm, PasswordResetForm
from user_profile.models import Profile

class CustomPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': 'Enter Your Email'}))


class CustomPasswordChangeForm(PasswordChangeForm):
   old_password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Enter Old password', 'autocomplete': False}))
   new_password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Enter New password', 'autocomplete': False}))
   new_password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Confirm New password', 'autocomplete': False}))
   
class CustomSetPasswordForm(SetPasswordForm):
    new_password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Enter New Password', 'class': 'new_password1'}))
    new_password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Confirm Password', 'class': 'new_password2'}))

class CodeForm(forms.ModelForm):
    number = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Enter the verification code'}))

    class Meta:
        model = Code
        fields = ['number']

class EmailorPhoneAuthentication(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'autofocus': True, 'placeholder': 'Enter your email or phone number'})
    )
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))


class SignupForm(forms.ModelForm):
    first_name = forms.CharField(max_length=25, widget=forms.TextInput(attrs={'placeholder': 'First Name'}))
    last_name = forms.CharField(max_length=25, widget=forms.TextInput(attrs={'placeholder': 'Last Name'}))
    username = forms.CharField(max_length=25, widget=forms.TextInput(attrs={'placeholder': 'Enter Username eg. @user_01'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': 'Enter Your Email'}))
    phone_number = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Enter Your Phone Number'}), max_length=15)
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password'}))

    class Meta:
        model = CustomUser
        fields = ['first_name','last_name', 'username','email', 'phone_number', 'password']

    def clean_username(self):
        data= self.cleaned_data['username']
        if CustomUser.objects.filter(username=data).exists():
            raise forms.ValidationError('The username you entered exists, change the last number at @user_01 to a different number and try again')
        return data

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Password does not match!, Try again')
        return cd['password2']
    
    def clean_email(self):
        data = self.cleaned_data['email']
        if CustomUser.objects.filter(email=data).exists():
            raise forms.ValidationError('Email already exists!!')
        return data
    
    def clean_phone_number(self):
        data = self.cleaned_data['phone_number']
        if CustomUser.objects.filter(phone_number=data).exists():
            raise forms.ValidationError('Your number already exists')
        return data
    
    def save(self, commit=True):
        user = CustomUser(
            first_name = self.cleaned_data['first_name'],
            last_name = self.cleaned_data['last_name'],
            username = self.cleaned_data['username'],
            email = self.cleaned_data['email'],
            phone_number = self.cleaned_data['phone_number'],
        )
        user.set_password(self.cleaned_data['password'])
        
        if commit:
            user.save()
            Profile.objects.create(user=user)
        return user

account/views.py
from django.urls import reverse_lazy
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from .models import CustomUser
from django.contrib.auth import get_backends
from django.contrib.auth.views import LoginView, PasswordChangeView, PasswordResetView, PasswordResetConfirmView
from .forms import SignupForm, EmailorPhoneAuthentication, CodeForm, CustomSetPasswordForm, CustomPasswordChangeForm, CustomPasswordResetForm
from django.contrib.auth.forms import AuthenticationForm

from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from .utils import send_sms

from user_profile.models import Profile

@login_required
def home_view(request):
    custom = CustomUser.objects.exclude(id=request.user.id)
    return render(request, 'home.html', {'custom': custom})

class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    form_class = CustomSetPasswordForm

    def get_success_url(self):
        return reverse_lazy('account:login')
    
class CustomPasswordRest(PasswordResetView):
    form_class = CustomPasswordResetForm

    def get_success_url(self):
        return reverse_lazy('account:password_reset_done')
    
class CustomPasswordChange(PasswordChangeView):
    form_class = CustomPasswordChangeForm
    template_name = 'registration/password_change_form.html'

    def get_success_url(self):
        return reverse_lazy('account:login')
    
class CustomLoginView(LoginView):
    template_name = 'registration/login.html'


    def get_success_url(self): 
        return reverse_lazy('products:product_list')


""" def verify_view(request):
    form = CodeForm(request.POST)
    request.session['pk'] = request.user.pk
    pk = request.session.get('pk')
    if pk:
        user = CustomUser.objects.get(pk=pk)
        code = user.code
        code_user = f'{user.first_name}: {code}'
        if not request.POST:
            print(code_user)
            #send_sms(code, user.phone_number, user.first_name)
        if form.is_valid():
            num = form.cleaned_data.get('number')
            if str(code) == num:
                code.save()
                login(request, user, backend='account.authenticated.EmailorPhoneBackend')
                return redirect('account:home')
            else:
                return render(request, 'verify.html', {'error': 'The code you entered is wrong try again'})
    return render(
        request,
        'verify.html',
        {'form': form}
    )
 """
def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('account:login')
    else:
        form = SignupForm()
    return render(
        request,
        'registration/signup.html',
        {'form': form}
    )

def logout_form(request):
    return render(request, 'registration/logout_form.html', {})

account/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title%}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
    <div class="container">
        <div class="mini-container">
            <div class="sidebar">
                <div class="logo">
                    <h1>
                        CampusConnect+
                    </h1>
                </div>
                <div class="navbar-panel">
                    <ul>
                        <a href="#"><li> Home </li></a>
                        <a href="{% url 'products:product_list' %}"><li> Products</li></a>
                        <a href="{% url 'user_profile:profile' request.user.username %}"><li> Profile </li></a>
                        <a href="#"><li> About us </li></a>
                        <a href="#"><li>Contact</li></a>
                        {% if request.user.is_authenticated %}
                        <a href="{% url 'account:form'%}"><li> Logout </li></a>
                        <a href="{% url 'account:password_change'%}"><li> Chage Password </li></a>
                        {% else %}
                            <li><a href="{% url 'account:login' %}"> Log in </a></li>
                            <li><a href="{% url 'account:signup' %}"> Sign Up </a></li>
                        {% endif %}
                    </ul>
                </div>

                <div class="profile">
                    <div class="img">
                        <img src="{% if request.user.profile.profile_photo %} {{ request.user.profile.profile_photo.url}} {% else %} {% static 'images/no_image.jpg' %}{% endif %}" alt="image goes here">
                    </div>
                    <div class="username">
                        <h3>{{ request.user.first_name }} {{ request.user.last_name }}</h3>
                    </div>
                </div>

                <div class="post_product">
                    <a href="{% url 'products:create_product'%}"> Post Product </a>
                </div>
            </div>
            <div class="">
                {% block content%}
                {% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

account/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Hello World!! {{ request.user.username }}</h1>

    {% if request.user.is_authenticated %}
        <button><a href="{% url 'account:form' %}"> Logout </a></button>
        <button><a href="{% url 'account:password_change' %}"> Change Password </a></button>
        <button><a href="{% url 'user_profile:profile_edit' %}"> Edit profile </a></button>
        <button><a href="{% url 'products:product_list' %}"> Products </a></button>
        <button><a href="{% url 'user_profile:profile' request.user.username %}"> Profile </a></button>
    {% else %}
        <button><a href="{% url 'account:signup' %}"> singup </a></button>
        <button><a href="{% url 'account:login' %}"> Login </a></button>
    {% endif %}

    <div class="profiles">
        {% for c_user in custom %}
            <a href="{% url 'user_profile:profile' c_user.username %}">
                <h4>
                    {{ c_user.profile }}
                </h4>

                <img src="{% if c_user.profile.profile_photo %} {{ c_user.profile.profile_photo.url }}{%else%}{% static 'images/no_image.jpg' %}{% endif %}" alt="">
            </a>
        {% endfor %}
    </div>
</body>
</html>

account/templates/verify.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div>
        {% if error %}
            <p>{{ error }}</p>
        {% else %}
            <p>Enter the code you received here </p>
        {% endif %}
        <form action="{% url 'account:verify' %}" method="post" autocomplete="off">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Verify</button>
        </form>
    </div>
</body>
</html>