account/urls.py
from django.urls import path
from .views import signup, CustomLoginView, logout_form, home_view,CustomPasswordChange, CustomPasswordRest, CustomPasswordResetConfirmView
from django.contrib.auth.views import (LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, PasswordResetConfirmView, PasswordResetDoneView, PasswordResetCompleteView)
from .forms import EmailorPhoneAuthentication

app_name = 'account'

urlpatterns = [
    path('login/', CustomLoginView.as_view(authentication_form=EmailorPhoneAuthentication), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password-change/', CustomPasswordChange.as_view(), name='password_change'),
    path('password-reset/', CustomPasswordRest.as_view(), name='password_reset'),
    path('password-reset/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('password-reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'), 
    #path('verify/', verify_view, name='verify'),
    path('signup/', signup, name='signup'),
    path('logout/form/', logout_form, name='form'),
    path('', home_view, name='home')
]

campus_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from user_profile.views import user_profile

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', include('django.contrib.auth.urls')),
    path('account/', include('account.urls', namespace='account')),
    path('profile/', include('user_profile.urls', namespace='user_profile')),
    path('', include('products.urls', namespace='products')),
    path('social-auth/', include('social_django.urls', namespace='social')),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

products/urls.py
from django.urls import path
from .views import product_list, create_product_view, product_detail, edit_product, delete_product, product_search

app_name = 'products'

urlpatterns = [
    path('', product_list, name='product_list'),
    path('products/<slug:category_slug>/', product_list, name='product_list_slug'),
    path('<int:id>/<slug:slug>', product_detail, name='product_detail'),
    path('post_product/', create_product_view, name='create_product'),
    path('<int:id>/<slug:slug>/edit/', edit_product, name='edit_product'),
    path('<int:id>/<slug:slug>/del/', delete_product, name='delete'),
    path('search/', product_search, name='search')
]

user_profile/urls.py
from django.urls import path
from .views import edit, user_profile

app_name = 'user_profile' 

urlpatterns = [
    path('edit/', edit, name='profile_edit'),
    path('<username>/', user_profile, name='profile')
]

products/models.py
from django.db import models
from account.models import CustomUser
from django.utils.text import slugify
from django.urls import reverse

class Category(models.Model):
    CATEGORY_CHOICES = [
        ('clothes', 'Clothes'),
        ('phones', 'Phones'),
        ('laptops', 'Laptops'),
        ('food', 'Food'),
        ('art', 'Art Works'),
    ]

    name = models.CharField(max_length=20, choices=CATEGORY_CHOICES, blank=True)
    slug = models.SlugField(max_length=20, blank=True)

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

        indexes = [
            models.Index(fields=['name'])
        ]
        ordering = ['name']

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('products:product_list_slug', args=[self.slug])
    
    def __str__(self):
        return self.name 
    

class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products')
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product_image/%Y/%m/%d', blank=True, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created']
        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-created']),
        ]

    def get_absolute_url(self):
        return reverse('products:product_detail', args=[self.id, self.slug])
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)
    
    def __str__(self):
        return self.name

products/forms.py
from django import forms
from .models import Category, Product

""" class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']
 """
class SearchForm(forms.Form):
    query = forms.CharField(widget=forms.TextInput(attrs={"Placeholder": 'Find product or user'}))

class ProductForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Product name'}))
    description = forms.CharField(widget=forms.Textarea(attrs={'placeholder':'Product description'}))
    price = forms.DecimalField(widget=forms.NumberInput(attrs={'placeholder': 'Product price'}))
    image = forms.ImageField(label='image_field')
    
    category = forms.ModelChoiceField(
        queryset=Category.objects.all(),
        empty_label='Select category'
    )

    class Meta:
        model = Product
        fields = [
            'name',
            'image',
            'description',
            'price',
            'category',
        ]

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)


    def save(self, commit=True):
        product = super().save(commit=False)
        print("User:", self.user) 
        
        if self.user:
            product.user = self.user
            print('User:', product.user)
        if commit:
            product.save()
        return product
    
class EditProductForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Product name'}))
    description = forms.CharField(widget=forms.Textarea(attrs={'placeholder':'Product description'}))
    price = forms.DecimalField(widget=forms.NumberInput(attrs={'placeholder': 'Product price'}))
    
    category = forms.ModelChoiceField(
        queryset=Category.objects.all(),
        empty_label='Select category'
    )

    class Meta:
        model = Product
        fields = [
            'name',
            'image',
            'description',
            'price',
            'category',
        ]

products/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Product, Category
from .forms import ProductForm, EditProductForm, SearchForm
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.contrib.postgres.search import SearchVector

def product_search(request):
    form = SearchForm()
    query = None
    results = []

    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = (
                Product.objects.annotate(
                    search = SearchVector('name', 'user'),
                ).filter(search=query)
            )

    return render(
        request,
        'products/search.html',
        {
            'form': form,
            'query': query,
            'results': results,
        }
    )


@login_required
def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.all()

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    paginator = Paginator(products, 9)
    page_number = request.GET.get('page', 1)
    products = paginator.page(page_number)
    
    return render(
        request,
        'products/index.html',
        {
            'category': category,
            'categories': categories,
            'products': products,
        }
    )

def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug)
    
    return render(
        request,
        'products/product_detail.html',
        {
            'product': product
        }
    )

@login_required 
def create_product_view(request):
    if request.method == 'POST':
        form = ProductForm(data = request.POST, files = request.FILES, user = request.user)
        if form.is_valid():
            form.save()
            return redirect('products:product_list')
        
    else:
        form = ProductForm(user = request.user)
    context = {
        'form': form
    }

    return render(
        request,
        'products/create_product.html',
        context
    )

@login_required 
def edit_product(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug)

    if request.method == 'POST':
        product_form = EditProductForm(instance=product, data=request.POST, files = request.FILES)
        if product_form.is_valid():
            product_form.save()
            return redirect('products:product_detail', id=product.id, slug=product.slug)
    else:
        product_form = EditProductForm(instance=product)

    return render(
        request,
        'products/edit_product.html',
        {
            'product_form': product_form
        }
    )

@login_required
def delete_product(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug)

    if request.method == 'POST':
        product.delete()
        
        return redirect('user_profile:profile', username=product.user.username)

    return render(
        request,
        'products/delete.html',
        {
            'product': product
        }
    )

products/templates/products/create_product.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Pacifico&family=Poppins:ital,wght@0,200;0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,600;1,700&display=swap');
        /* root variables */

        :root {
            --primary-color: #1DA1F2;
            --background-color: #14171A;
            --light-gray: #666666;
            --white-color: #ffffff;
            --sidebar-background: #1A1D23;
            --primary-text: #ffffff;
            --link-text: #1DA1F2;
            --secondary-text: #666666;
            --tertiary-text: #808080;
            --border-color: #2F3336;
            --shadow-color: #000000;
            --hover-color: #1A1D23;
            --profile-background-color: #23272A;
        }

        *{
            padding: 0;
            margin: 0;
            list-style: none;
            text-decoration: none;
            outline: 0;
            appearance: none;
            box-sizing: border-box;
            border: 0;
            font-family: 'Poppins', sans-serif;
        }

        .create_container{
            width: 100vw;
            height: 100vh;
            font-size: 0.88rem;
            background: var(--background-color);
            user-select: none;
            overflow-x: hidden;
            display: grid;
            place-items: center;
        }

        .create_container form{
            display: flex;
            flex-direction: column;
            gap: 10px;
            width: 400px;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0px 0px 10px var(--shadow-color);
        }

        
        form p label{
            display: none;
        }

        input{
            width: 350px;
            display: block;
            background-color: transparent;
            margin: auto;
            border: 1.5px solid var(--white-color);
            border-radius: 5px;
            padding: 10px 40px;
            text-align: center;
            margin-bottom: 20px;
            color: var(--white-color);
        }
        
        textarea{
            width: 350px;
            height: 100px;
            background-color: transparent;
            border: 1.5px solid var(--white-color);
            border-radius: 5px;
            padding: 10px;
            margin-left: 5px;
            color: var(--white-color);
            resize: none;
        }

        select {
            width: 350px;
            background-color: transparent;
            border: 1.5px solid var(--white-color);
            border-radius: 5px;
            padding: 10px;
            margin-left: 5px;
            color: var(--white-color);
            text-align: center;
        }

        option{
            width: 250px;
            background-color: var(--background-color);
            border: 1.5px solid var(--white-color);
            border-radius: 5px;
            padding: 10px;
            margin-left: 5px;
            color: var(--white-color);
            text-align: center;
        }

        button {
            background-color: var(--primary-color);
            color: var(--white-color);
            margin: auto;
            width: 350px;
            display: block;
            border-radius: 5px;
            padding: 10px 0;
            cursor: pointer;
            text-align: center;
        }

        form h3 {
            padding: 10px 20px;
            color: var(--white-color);
            text-align: center;
            font-size: 18px;
            margin: 0 10px;
        }
    </style>
</head>
<body>
    <div class="create_container">
       
        <form action="" method="post" enctype="multipart/form-data">
            <h3>
                Upload Product
            </h3>
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Post</button>
        </form>
    </div>
</body>
</html>

products/templates/products/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Pacifico&family=Poppins:ital,wght@0,200;0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,600;1,700&display=swap');
        /* root variables */

        :root {
            --primary-color: #1DA1F2;
            --background-color: #14171A;
            --light-gray: #666666;
            --white-color: #ffffff;
            --sidebar-background: #1A1D23;
            --primary-text: #ffffff;
            --link-text: #1DA1F2;
            --secondary-text: #666666;
            --tertiary-text: #808080;
            --border-color: #2F3336;
            --shadow-color: #000000;
            --hover-color: #1A1D23;
            --profile-background-color: #23272A;
        }

        *{
            padding: 0;
            margin: 0;
            list-style: none;
            text-decoration: none;
            outline: 0;
            appearance: none;
            box-sizing: border-box;
            border: 0;
            font-family: 'Poppins', sans-serif;
        }

        .create_container{
            width: 100vw;
            height: 100vh;
            font-size: 0.88rem;
            background: var(--background-color);
            user-select: none;
            overflow-x: hidden;
            display: grid;
            place-items: center;
        }

        .create_container form{
            display: flex;
            flex-direction: column;
            gap: 10px;
            width: 400px;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0px 0px 10px var(--shadow-color);
        }

        
        form p label{
            display: none;
        }

        input{
            width: 350px;
            display: block;
            background-color: transparent;
            margin: auto;
            border: 1.5px solid var(--white-color);
            border-radius: 5px;
            padding: 10px 40px;
            text-align: center;
            margin-bottom: 20px;
            color: var(--white-color);
        }
        
        textarea{
            width: 350px;
            height: 100px;
            background-color: transparent;
            border: 1.5px solid var(--white-color);
            border-radius: 5px;
            padding: 10px;
            margin-left: 5px;
            color: var(--white-color);
            resize: none;
        }

        select {
            width: 350px;
            background-color: transparent;
            border: 1.5px solid var(--white-color);
            border-radius: 5px;
            padding: 10px;
            margin-left: 5px;
            color: var(--white-color);
            text-align: center;
        }

        option{
            width: 250px;
            background-color: var(--background-color);
            border: 1.5px solid var(--white-color);
            border-radius: 5px;
            padding: 10px;
            margin-left: 5px;
            color: var(--white-color);
            text-align: center;
        }

        button {
            background-color: var(--primary-color);
            color: var(--white-color);
            margin: auto;
            width: 350px;
            display: block;
            border-radius: 5px;
            padding: 10px 0;
            cursor: pointer;
            text-align: center;
        }

        form h3 {
            padding: 10px 20px;
            color: var(--white-color);
            text-align: center;
            font-size: 18px;
            margin: 0 10px;
        }
    </style>
</head>
<body>
    <div class="create_container">
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <h3>
                Are you sure you want to delete "{{ product.name }}"
            </h3>
    
            <button type="submit"> Yes </button>
        </form>
    </div>
    
</body>
</html>

products/templates/products/edit_product.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Pacifico&family=Poppins:ital,wght@0,200;0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,600;1,700&display=swap');
        /* root variables */

        :root {
            --primary-color: #1DA1F2;
            --background-color: #14171A;
            --light-gray: #666666;
            --white-color: #ffffff;
            --sidebar-background: #1A1D23;
            --primary-text: #ffffff;
            --link-text: #1DA1F2;
            --secondary-text: #666666;
            --tertiary-text: #808080;
            --border-color: #2F3336;
            --shadow-color: #000000;
            --hover-color: #1A1D23;
            --profile-background-color: #23272A;
        }

        *{
            padding: 0;
            margin: 0;
            list-style: none;
            text-decoration: none;
            outline: 0;
            appearance: none;
            box-sizing: border-box;
            border: 0;
            font-family: 'Poppins', sans-serif;
        }

        .create_container{
            width: 100vw;
            height: 100vh;
            font-size: 0.88rem;
            background: var(--background-color);
            user-select: none;
            overflow-x: hidden;
            display: grid;
            place-items: center;
        }

        .create_container form{
            display: flex;
            flex-direction: column;
            gap: 10px;
            width: 400px;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0px 0px 10px var(--shadow-color);
        }

        
        form p label{
            display: none;
        }

        input{
            width: 350px;
            display: block;
            background-color: transparent;
            margin: auto;
            border: 1.5px solid var(--white-color);
            border-radius: 5px;
            padding: 10px 40px;
            text-align: center;
            margin-bottom: 20px;
            color: var(--white-color);
        }
        
        textarea{
            width: 350px;
            height: 100px;
            background-color: transparent;
            border: 1.5px solid var(--white-color);
            border-radius: 5px;
            padding: 10px;
            margin-left: 5px;
            color: var(--white-color);
            resize: none;
        }

        select {
            width: 350px;
            background-color: transparent;
            border: 1.5px solid var(--white-color);
            border-radius: 5px;
            padding: 10px;
            margin-left: 5px;
            color: var(--white-color);
            text-align: center;
        }

        option{
            width: 250px;
            background-color: var(--background-color);
            border: 1.5px solid var(--white-color);
            border-radius: 5px;
            padding: 10px;
            margin-left: 5px;
            color: var(--white-color);
            text-align: center;
        }

        button {
            background-color: var(--primary-color);
            color: var(--white-color);
            margin: auto;
            width: 350px;
            display: block;
            border-radius: 5px;
            padding: 10px 0;
            cursor: pointer;
            text-align: center;
        }

        input[type='checkbox']{
            display: none;
        }

        form p {
            color: var(--white-color);
        }

        form h3 {
            padding: 10px 20px;
            color: var(--white-color);
            text-align: center;
            font-size: 18px;
            margin: 0 10px;
        }
    </style>
</head>
<body>
    <div class="create_container">
        <form action="" method="post" enctype="multipart/form-data">
            <h3>
                Edit Product
            </h3>

            {% csrf_token %}
            {{ product_form.as_p }}
            <button type="submit">Edit</button>
        </form>
    </div>
    
</body>
</html>

products/templates/products/index.html
{% extends 'base.html' %}
{% load static %}
{% load custom_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block content %}
    <div class="product_container">
        <div class="product_nav">
            <ul>
                <li {% if not category %} class="selected" {% endif %}>
                    <a href="{% url 'products:product_list' %}">All</a>
                </li>
                {% for c in categories %}
                    <li {% if category.slug == c.slug %} class="selected" {% endif %}>
                        <a href="{{ c.get_absolute_url }}"> {{ c.name }}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>

        <div class="products">
            <div class="category">
                <h1> {% if category %} {{ category.name }} {% else %} Products {% endif %}</h1>
                <a href="{% url 'products:search' %}"> Search product </a>
            </div>
        
            {% if products %}
                <div class="product_items">
                {% for product in products %}
                        <div class="items">
                            <div class="product_img">
                                <a href="{{ product.get_absolute_url }}">
                                    <img src="{% if product.image %}{{ product.image.url}} {% else %} {% static 'images/no_image_available.png'%} {% endif %}" alt="{{ product.name }}">
                                </a>
                            </div>

                            <div class="product_name">
                                <div>
                                    <h3>
                                        {{ product.name }}
                                    </h3>
                                </div>
                                <div>
                                    <p>
                                        Ghc {{ product.price }}
                                    </p>
                                </div>
                            </div>

                            <div class="product_owner">
                                <div class="profile_pic">
                                    <a href="{% url 'user_profile:profile' product.user.username%}">
                                        <img src="{% if product.user.profile.profile_photo %} {{ product.user.profile.profile_photo.url }} {% else %} {% static 'images/no_image.jpg'%} {% endif %}" alt="{{ product.user.first_name}}">
                                    </a>
                                </div>
                                <a href="{% url 'user_profile:profile' product.user.username%}">
                                    <div class="username">
                                        <h3>
                                            {{ product.user.first_name}} {{ product.user.last_name }}
                                        </h3>
                                        <p>
                                            {{ product.created | format_created_date }}
                                        </p>
                                    </div>
                                </a>
                            </div>
                        </div>
                        
                {% endfor %}
                </div>
            {% else %}
                <p class="no_product">
                    No products uploaded in this category
                </p>
            {% endif %}
        </div>
        {% include "products/paginator.html" with page=products%}
    </div>
    {% endblock %}
</body>
</html>

products/templates/products/paginator.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <style>
        :root {
            --primary-color: #1DA1F2;
            --background-color: #14171A;
            --light-gray: #666666;
            --white-color: #ffffff;
            --sidebar-background: #1A1D23;
            --primary-text: #ffffff;
            --link-text: #1DA1F2;
            --secondary-text: #666666;
            --tertiary-text: #808080;
            --border-color: #2F3336;
            --shadow-color: #000000;
            --hover-color: #1A1D23;
            --profile-background-color: #23272A;
        }
        .pagination {
            margin-left: 20px;
            margin-top: 30px;
            margin-bottom: 20px;
        }

        .pagination .step-links a{
            color: var(--link-text);
        }

        .pagination .current {
            color: var(--white-color);
        }

        .pagination a{
            color: var(--link-text);
        }

    </style>
</head>
<body>
    <div class="pagination">
        <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
        </span>
    </div>
</body>
</html>

products/templates/products/product_detail.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block content %}
        <div class="detail_container">
            <div class="detail">
                <div class="detail_img">
                    <img src="{% if product.image %}{{ product.image.url}}{% else%}{% static 'images/no_image_available.png'%}{% endif %}" alt="{{ product.name }}">
                </div>
                <div class="details">
                    <div class="name_price">
                        <h2>{{ product.name }}</h2>
                        <p> Ghc {{ product.price }} </p>
                        <p class="prod_desc">
                            {{ product.description }}
                        </p>
                    </div>
                    <div class="buttons_for">
                        {% if request.user == product.user %}
                            <a href="{% url 'products:edit_product' product.id product.slug %}">
                                Edit Product
                            </a>

                            <a href="{% url 'products:delete' product.id product.slug %}">
                                Delete
                            </a>
                        {% endif %}
                    </div>

                    <a href="{% url 'user_profile:profile' product.user.username %}">
                        <div class="prod_owner">
                            <img src="{% if product.user.profile.profile_photo %}{{ product.user.profile.profile_photo.url}}{% else %}{% static 'images/no_image.jpg'%}{% endif %}" alt="{{ product.user.first_name}}">

                            <h3>
                                {{ product.user.first_name }} {{ product.user.last_name }}
                            </h3>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    {% endblock %}
</body>
</html>